### ISSUE TITLE
Something is wrong with devicons.min.css

### ISSUE THREAD

**Issue by jjsaunier** [vorillaz/devicons#33]
I dont know what are you doing with git, and how can you have pushed this on the repo when your file is in conflict :O. It's sense to never happened because git stop you until you have entirely merge your working tree :D

People using your lib accross versionning platform have some troubles ... 

``` css
/*!
 *  Devicons 1.5.0 made by Theodore Vorillas / http://vorillaz.com 
 */
<<<<<<< HEAD
@font-face{font-family:'devicons';src:url("../fonts/devicons.eot?xqxft6");src:url("../fonts/devicons.eot?#iefixxqxft6") format("embedded-opentype"),url("../fonts/devicons.woff?xqxft6") format("woff"),url("../fonts/devicons.ttf?xqxft6") format("truetype"),url("../fonts/devicons.svg?xqxft6#devicons") format("svg");font-weight:normal;font-style:normal}.devicons{font-family:'devicons';speak:none;font-style:normal;font-weight:normal;font-variant:normal;text-transform:none;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}.devicons-git:before{content:"\e602"}.devicons-git_compare:before{content:"\e628"}.devicons-git_branch:before{content:"\e625"}.devicons-git_commit:before{content:"\e629"}.devicons-git_pull_request:before{content:"\e626"}.devicons-git_merge:before{content:"\e627"}.devicons-bitbucket:before{content:"\e603"}.devicons-github_alt:before{content:"\e608"}.devicons-github_badge:before{content:"\e609"}.devicons-github:before{content:"\e60a"}.devicons-github_full:before{content:"\e617"}.devicons-java:before{content:"\e638"}.devicons-ruby:before{content:"\e639"}.devicons-scala:before{content:"\e637"}.devicons-python:before{content:"\e63c"}.devicons-go:before{content:"\e624"}.devicons-ruby_on_rails:before{content:"\e63b"}.devicons-django:before{content:"\e61d"}.devicons-markdown:before{content:"\e63e"}.devicons-php:before{content:"\e63d"}.devicons-mysql:before{content:"\e604"}.devicons-streamline:before{content:"\e605"}.devicons-database:before{content:"\e606"}.devicons-laravel:before{content:"\e63f"}.devicons-javascript:before{content:"\e64e"}.devicons-angular:before{content:"\e653"}.devicons-backbone:before{content:"\e652"}.devicons-coffeescript:before{content:"\e651"}.devicons-jquery:before{content:"\e650"}.devicons-modernizr:before{content:"\e620"}.devicons-jquery_ui:before{content:"\e654"}.devicons-ember:before{content:"\e61b"}.devicons-dojo:before{content:"\e61c"}.devicons-nodejs:before{content:"\e619"}.devicons-nodejs_small:before{content:"\e618"}.devicons-javascript_shield:before{content:"\e64f"}.devicons-bootstrap:before{content:"\e647"}.devicons-sass:before{content:"\e64b"}.devicons-css3_full:before{content:"\e64a"}.devicons-css3:before{content:"\e649"}.devicons-html5:before{content:"\e636"}.devicons-html5_multimedia:before{content:"\e632"}.devicons-html5_device_access:before{content:"\e633"}.devicons-html5_3d_effects:before{content:"\e635"}.devicons-html5_connectivity:before{content:"\e634"}.devicons-ghost_small:before{content:"\e614"}.devicons-ghost:before{content:"\e61f"}.devicons-magento:before{content:"\e640"}.devicons-joomla:before{content:"\e641"}.devicons-jekyll_small:before{content:"\e60d"}.devicons-drupal:before{content:"\e642"}.devicons-wordpress:before{content:"\e60b"}.devicons-grunt:before{content:"\e64c"}.devicons-bower:before{content:"\e64d"}.devicons-npm:before{content:"\e61e"}.devicons-yahoo_small:before{content:"\e62b"}.devicons-yahoo:before{content:"\e615"}.devicons-bing_small:before{content:"\e600"}.devicons-windows:before{content:"\e60f"}.devicons-linux:before{content:"\e612"}.devicons-ubuntu:before{content:"\e63a"}.devicons-android:before{content:"\e60e"}.devicons-apple:before{content:"\e611"}.devicons-appstore:before{content:"\e613"}.devicons-phonegap:before{content:"\e630"}.devicons-blackberry:before{content:"\e623"}.devicons-stackoverflow:before{content:"\e610"}.devicons-techcrunch:before{content:"\e62c"}.devicons-codrops:before{content:"\e62f"}.devicons-css_tricks:before{content:"\e601"}.devicons-smashing_magazine:before{content:"\e62d"}.devicons-netmagazine:before{content:"\e62e"}.devicons-codepen:before{content:"\e616"}.devicons-cssdeck:before{content:"\e62a"}.devicons-hackernews:before{content:"\e61a"}.devicons-dropbox:before{content:"\e607"}.devicons-google_drive:before{content:"\e631"}.devicons-visualstudio:before{content:"\e60c"}.devicons-unity_small:before{content:"\e621"}.devicons-rasberry_pi:before{content:"\e622"}.devicons-chrome:before{content:"\e643"}.devicons-ie:before{content:"\e644"}.devicons-firefox:before{content:"\e645"}.devicons-opera:before{content:"\e646"}.devicons-safari:before{content:"\e648"}.devicons-swift:before{content:"\e655"}.devicons-symfony:before{content:"\e656"}.devicons-symfony_badge:before{content:"\e657"}.devicons-less:before{content:"\e658"}.devicons-stylus:before{content:"\e659"}.devicons-trello:before{content:"\e65a"}.devicons-atlassian:before{content:"\e65b"}.devicons-jira:before{content:"\e65c"}.devicons-envato:before{content:"\e65d"}.devicons-snap_svg:before{content:"\e65e"}.devicons-raphael:before{content:"\e65f"}.devicons-google_analytics:before{content:"\e660"}.devicons-compass:before{content:"\e661"}.devicons-onedrive:before{content:"\e662"}.devicons-gulp:before{content:"\e663"}.devicons-atom:before{content:"\e664"}.devicons-cisco:before{content:"\e665"}.devicons-nancy:before{content:"\e666"}.devicons-clojure:before{content:"\e668"}.devicons-clojure_alt:before{content:"\e66a"}.devicons-perl:before{content:"\e669"}.devicons-celluloid:before{content:"\e66b"}.devicons-w3c:before{content:"\e66c"}.devicons-redis:before{content:"\e66d"}.devicons-postgresql:before{content:"\e66e"}.devicons-webplatform:before{content:"\e66f"}.devicons-jenkins:before{content:"\e667"}.devicons-requirejs:before{content:"\e670"}.devicons-opensource:before{content:"\e671"}.devicons-typo3:before{content:"\e672"}.devicons-uikit:before{content:"\e673"}.devicons-doctrine:before{content:"\e674"}.devicons-groovy:before{content:"\e675"}.devicons-nginx:before{content:"\e676"}.devicons-haskell:before{content:"\e677"}.devicons-zend:before{content:"\e678"}.devicons-gnu:before{content:"\e679"}.devicons-yeoman:before{content:"\e67a"}.devicons-heroku:before{content:"\e67b"}.devicons-debian:before{content:"\e67d"}.devicons-travis:before{content:"\e67e"}.devicons-dotnet:before{content:"\e67f"}.devicons-codeigniter:before{content:"\e680"}.devicons-javascript_badge:before{content:"\e681"}.devicons-yii:before{content:"\e682"}.devicons-msql_server:before{content:"\e67c"}.devicons-composer:before{content:"\e683"}.devicons-krakenjs_badge:before{content:"\e684"}.devicons-krakenjs:before{content:"\e685"}.devicons-mozilla:before{content:"\e686"}.devicons-firebase:before{content:"\e687"}.devicons-sizzlejs:before{content:"\e688"}.devicons-creativecommons:before{content:"\e689"}.devicons-creativecommons_badge:before{content:"\e68a"}.devicons-mitlicence:before{content:"\e68b"}.devicons-senchatouch:before{content:"\e68c"}.devicons-bugsense:before{content:"\e68d"}.devicons-extjs:before{content:"\e68e"}.devicons-mootools_badge:before{content:"\e68f"}.devicons-mootools:before{content:"\e690"}.devicons-ruby_rough:before{content:"\e691"} */;
=======
 * @font-face{font-family:'devicons';src:url("../fonts/devicons.eot?xqxft6");src:url("../fonts/devicons.eot?#iefixxqxft6") format("embedded-opentype"),url("../fonts/devicons.woff?xqxft6") format("woff"),url("../fonts/devicons.ttf?xqxft6") format("truetype"),url("../fonts/devicons.svg?xqxft6#devicons") format("svg");font-weight:normal;font-style:normal}.devicons{font-family:'devicons';speak:none;font-style:normal;font-weight:normal;font-variant:normal;text-transform:none;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}.devicons-git:before{content:"\e602"}.devicons-git_compare:before{content:"\e628"}.devicons-git_branch:before{content:"\e625"}.devicons-git_commit:before{content:"\e629"}.devicons-git_pull_request:before{content:"\e626"}.devicons-git_merge:before{content:"\e627"}.devicons-bitbucket:before{content:"\e603"}.devicons-github_alt:before{content:"\e608"}.devicons-github_badge:before{content:"\e609"}.devicons-github:before{content:"\e60a"}.devicons-github_full:before{content:"\e617"}.devicons-java:before{content:"\e638"}.devicons-ruby:before{content:"\e639"}.devicons-scala:before{content:"\e637"}.devicons-python:before{content:"\e63c"}.devicons-go:before{content:"\e624"}.devicons-ruby_on_rails:before{content:"\e63b"}.devicons-django:before{content:"\e61d"}.devicons-markdown:before{content:"\e63e"}.devicons-php:before{content:"\e63d"}.devicons-mysql:before{content:"\e604"}.devicons-streamline:before{content:"\e605"}.devicons-database:before{content:"\e606"}.devicons-laravel:before{content:"\e63f"}.devicons-javascript:before{content:"\e64e"}.devicons-angular:before{content:"\e653"}.devicons-backbone:before{content:"\e652"}.devicons-coffeescript:before{content:"\e651"}.devicons-jquery:before{content:"\e650"}.devicons-modernizr:before{content:"\e620"}.devicons-jquery_ui:before{content:"\e654"}.devicons-ember:before{content:"\e61b"}.devicons-dojo:before{content:"\e61c"}.devicons-nodejs:before{content:"\e619"}.devicons-nodejs_small:before{content:"\e618"}.devicons-javascript_shield:before{content:"\e64f"}.devicons-bootstrap:before{content:"\e647"}.devicons-sass:before{content:"\e64b"}.devicons-css3_full:before{content:"\e64a"}.devicons-css3:before{content:"\e649"}.devicons-html5:before{content:"\e636"}.devicons-html5_multimedia:before{content:"\e632"}.devicons-html5_device_access:before{content:"\e633"}.devicons-html5_3d_effects:before{content:"\e635"}.devicons-html5_connectivity:before{content:"\e634"}.devicons-ghost_small:before{content:"\e614"}.devicons-ghost:before{content:"\e61f"}.devicons-magento:before{content:"\e640"}.devicons-joomla:before{content:"\e641"}.devicons-jekyll_small:before{content:"\e60d"}.devicons-drupal:before{content:"\e642"}.devicons-wordpress:before{content:"\e60b"}.devicons-grunt:before{content:"\e64c"}.devicons-bower:before{content:"\e64d"}.devicons-npm:before{content:"\e61e"}.devicons-yahoo_small:before{content:"\e62b"}.devicons-yahoo:before{content:"\e615"}.devicons-bing_small:before{content:"\e600"}.devicons-windows:before{content:"\e60f"}.devicons-linux:before{content:"\e612"}.devicons-ubuntu:before{content:"\e63a"}.devicons-android:before{content:"\e60e"}.devicons-apple:before{content:"\e611"}.devicons-appstore:before{content:"\e613"}.devicons-phonegap:before{content:"\e630"}.devicons-blackberry:before{content:"\e623"}.devicons-stackoverflow:before{content:"\e610"}.devicons-techcrunch:before{content:"\e62c"}.devicons-codrops:before{content:"\e62f"}.devicons-css_tricks:before{content:"\e601"}.devicons-smashing_magazine:before{content:"\e62d"}.devicons-netmagazine:before{content:"\e62e"}.devicons-codepen:before{content:"\e616"}.devicons-cssdeck:before{content:"\e62a"}.devicons-hackernews:before{content:"\e61a"}.devicons-dropbox:before{content:"\e607"}.devicons-google_drive:before{content:"\e631"}.devicons-visualstudio:before{content:"\e60c"}.devicons-unity_small:before{content:"\e621"}.devicons-rasberry_pi:before{content:"\e622"}.devicons-chrome:before{content:"\e643"}.devicons-ie:before{content:"\e644"}.devicons-firefox:before{content:"\e645"}.devicons-opera:before{content:"\e646"}.devicons-safari:before{content:"\e648"}.devicons-swift:before{content:"\e655"}.devicons-symfony:before{content:"\e656"}.devicons-symfony_badge:before{content:"\e657"}.devicons-less:before{content:"\e658"}.devicons-stylus:before{content:"\e659"}.devicons-trello:before{content:"\e65a"}.devicons-atlassian:before{content:"\e65b"}.devicons-jira:before{content:"\e65c"}.devicons-envato:before{content:"\e65d"}.devicons-snap_svg:before{content:"\e65e"}.devicons-raphael:before{content:"\e65f"}.devicons-google_analytics:before{content:"\e660"}.devicons-compass:before{content:"\e661"}.devicons-onedrive:before{content:"\e662"}.devicons-gulp:before{content:"\e663"}.devicons-atom:before{content:"\e664"}.devicons-cisco:before{content:"\e665"}.devicons-nancy:before{content:"\e666"}.devicons-clojure:before{content:"\e668"}.devicons-clojure_alt:before{content:"\e66a"}.devicons-perl:before{content:"\e669"}.devicons-celluloid:before{content:"\e66b"}.devicons-w3c:before{content:"\e66c"}.devicons-redis:before{content:"\e66d"}.devicons-postgresql:before{content:"\e66e"}.devicons-webplatform:before{content:"\e66f"}.devicons-jenkins:before{content:"\e667"}.devicons-requirejs:before{content:"\e670"}.devicons-opensource:before{content:"\e671"}.devicons-typo3:before{content:"\e672"}.devicons-uikit:before{content:"\e673"}.devicons-doctrine:before{content:"\e674"}.devicons-groovy:before{content:"\e675"}.devicons-nginx:before{content:"\e676"}.devicons-haskell:before{content:"\e677"}.devicons-zend:before{content:"\e678"}.devicons-gnu:before{content:"\e679"}.devicons-yeoman:before{content:"\e67a"}.devicons-heroku:before{content:"\e67b"} */
>>>>>>> a37134208884d700f30b93ae3cc5c0442ae4937c
```
