### ISSUE TITLE
icons are not aligned correctly

### ISSUE THREAD

**Issue by luisrudge** [vorillaz/devicons#67]
![image](https://cloud.githubusercontent.com/assets/941075/7266157/c50f4d5c-e87b-11e4-9091-ebc51004f604.png)

repro:
http://codepen.io/anon/pen/BNaKvg

**Comment by luisrudge** [comment]
using this fixed:
```css
.devicons {
  vertical-align: text-bottom;
}
```
